# Generated by Django 6.0.6 on 2026-07-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='produits_videos/'),
        ),
    ]
