# Generated by Django 6.0.7 on 2026-07-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_alter_produit_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_whatsapp', models.CharField(help_text='Format international sans + ni espaces, ex: 22990000000', max_length=20)),
            ],
        ),
    ]
